### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'

### ISSUE THREAD

**Issue by xgxofdream** [GoogleCloudPlatform/tensorflow-without-a-phd#47]
when I run mnist_1.0_softmax.py in annconda cmd with python 3.6 on win10, it reported errors, who can help me with it? many thanks.
I type the followings:
`(base) F:\tensorflow-without-a-phd\tensorflow-mnist-tutorial>python mnist_1.0_softmax.py`

then it reported:
`Traceback (most recent call last):
  File "mnist_1.0_softmax.py", line 17, in <module>
    import tensorflowvisu
  File "F:\tensorflow-without-a-phd\tensorflow-mnist-tutorial\tensorflowvisu.py", line 27, in <module>
    tf.set_random_seed(0)
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'`

**Comment by xgxofdream** [comment]
well, it is about tensorflow version. 'set_random_seed' has changed to 'random.set_seed'.
and same issue: 'tf.decode_raw' to 'tf.io.decode_raw'

**Comment by martin-gorner** [comment]
Hello

The updated tutorial is here:
https://codelabs.developers.google.com/codelabs/cloud-tensorflow-mnist/#0

It links to the following updated notebooks:
[keras_01_mnist.ipynb](https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/keras_01_mnist.ipynb)
[keras_02_mnist_dense.ipynb](https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/keras_02_mnist_dense.ipynb)
[keras_03_mnist_dense_lrdecay_dropout.ipynb](https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/keras_03_mnist_dense_lrdecay_dropout.ipynb)
[keras_04_mnist_convolutional.ipynb](https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/keras_04_mnist_convolutional.ipynb)
[keras_05_mnist_batch_norm.ipynb](https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/keras_05_mnist_batch_norm.ipynb)

I left the other files in the repo because some videos still reference them but as you noticed, they are way behind the current version of Tensorflow.

**Comment by ankitgupta1729** [comment]
> well, it is about tensorflow version. 'set_random_seed' has changed to 'random.set_seed'.
> and same issue: 'tf.decode_raw' to 'tf.io.decode_raw'

Thank you. It worked for me
