### ISSUE TITLE
how to modify "tf_dataset.make_one_shot_iterator().get_next()"

### ISSUE THREAD

**Issue by xgxofdream** [GoogleCloudPlatform/tensorflow-without-a-phd#48]
in mnistdata.py, I met a similar issue related to tensorflow version. but I do not know how to modify it.

as [this link](https://www.tensorflow.org/api_docs/python/tf/compat/v1/data/make_one_shot_iterator) suggested, I got 'tf_dataset.make_one_shot_iterator()' to 'tf_dataset.compat.v1.data.make_one_shot_iterator'. But unfortunately it did not work! 
it reported: 
`
AttributeError: 'RepeatDataset' object has no attribute 'compat'`

anyone can kindly help me with it.

**Comment by martin-gorner** [comment]
Hello

The updated tutorial is here:
https://codelabs.developers.google.com/codelabs/cloud-tensorflow-mnist/#0

It links to the following updated notebooks:
[keras_01_mnist.ipynb](https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/keras_01_mnist.ipynb)
[keras_02_mnist_dense.ipynb](https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/keras_02_mnist_dense.ipynb)
[keras_03_mnist_dense_lrdecay_dropout.ipynb](https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/keras_03_mnist_dense_lrdecay_dropout.ipynb)
[keras_04_mnist_convolutional.ipynb](https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/keras_04_mnist_convolutional.ipynb)
[keras_05_mnist_batch_norm.ipynb](https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/keras_05_mnist_batch_norm.ipynb)

I left the other files in the repo because some videos still reference them but as you noticed, they are way behind the current version of Tensorflow.
